import time
import os

class color(): # just for python color fonts
  Black="\033[0;30m" #black
  Red="\33[0;31m" #red
  Green="\033[0;32m" # Green
  Yellow="\033[0;33m" # Yellow
  Blue="\033[0;34m" # Blue
  Purple="\033[0;35m" # Purple
  Cyan="\033[0;36m" # Cyan
  White="\033[0;37m" # White

  Greenbold="\033[5;32m"
  Redbold="\033[5;31m"
  Whitebold="\033[5;37m"
  Yellowbold="\033[5;33m"

os.system('clear')
time.sleep(0)
print(color.Whitebold+"lila dawya frhana")
time.sleep(1.5)
print("smaha ch3lat njom ach rbe7 li bkana")
time.sleep(2.5)
print("malk a ro7i z3fana")
time.sleep(1.5)
print("ma3lich wakha li sb9na ldnya 3rana")
time.sleep(2)
print("ch dnbi f'li drt ana")
time.sleep(1.5)
print("bach ghi nmse7 khoraft jeddi 9arn w sana")
time.sleep(3.3)
print("ila ghi fliyo stana")
time.sleep(1.5)
print("dnya 7lfat la fhmnaha ghi lmot b'lgana")
time.sleep(2.5)
os.system('clear')
print("2020 miladiya")
time.sleep(2.2)
print("ba9i dicor zawi ki zaman")
time.sleep(2)
print("l3aba f d3wa fdanya")
time.sleep(2)
print("salat mcha " +color.Redbold+"L7OB"+color.Whitebold+ " mcha l'aman")
time.sleep(1.7)
print("kolchi batal w kolchi robot")
time.sleep(2.4)
print("kolchi kayn kolchi bgha logo")
time.sleep(2)
os.system('clear')
print("kolc")
time.sleep(0.0)
os.system('clear')
print("kolch")
time.sleep(0.0)
os.system('clear')
print("kolchi ")
time.sleep(0.1)
os.system('clear')
print("kolchi fa")
time.sleep(0.1)
os.system('clear')
print("kolchi fahe")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w ")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w ko")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolc")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi ")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'd")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dny")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dnya w")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dnya w bn")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dnya w bnad")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dnya w bnadm ")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dnya w bnadm 3a")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dnya w bnadm 3add")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dnya w bnadm 3add f")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dnya w bnadm 3add f zn ")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dnya w bnadm 3add f znte")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dnya w bnadm 3add f zntet ")
time.sleep(0.1)
os.system('clear')
print("kolchi fahem w kolchi f'dnya w bnadm 3add f znteto ")
time.sleep(0.1)
os.system('clear')
print(color.Greenbold + '''
  ___  _   _ ____   ___  ____   ___  ____   ___  ____
 / _ \| | | |  _ \ / _ \| __ ) / _ \|  _ \ / _ \/ ___|
| | | | | | | |_) | | | |  _ \| | | | |_) | | | \___ \

| |_| | |_| |  _ <| |_| | |_) | |_| |  _ <| |_| |___) )
 \___/ \___/|_| \_ \___/|____/ \___/|_| \_|\___/|____/
         ''')
print(color.Yellowbold+"TA7IA L'7OBBI ❤️ROAYA❤️")


time.sleep(0.5)
os.system('clear')
print(color.Whitebold +"2020 miladiya")
time.sleep(1)
print("mataro siyarat")
time.sleep(1)
print("marb7na 9adiya")
time.sleep(2)
print("achno tatsayen men solala tarikheha kamel khorafat w sadiya")
time.sleep(2.7)
print("l7bes w lbtayn 3adiya")
time.sleep(2)
print("kayn li fahem kayn li st7la l9afiya")
time.sleep(3)
print("")
print("")
print("2020 miladiya")
time.sleep(1.5)
print("w mazal tanmoto b l'botat")
time.sleep(1.4)
print(color.Yellowbold+"W l3afiya")
time.sleep(1)
print(color.Whitebold+"2020 miladiya")
time.sleep(1.5)
print("w mazal jam3ana ghi l9r3a w lbakiya")
time.sleep(2)
print("makayn la ras lmal la 3imarat")
time.sleep(1.5)
print("kolchi sar7 fdmagho mkwi kiya")
time.sleep(2)
print("fmdina sghira "+color.Redbold+"7OBBI"+color.Whitebold+" 3dbni")
time.sleep(3)
print("li mata9ch")
time.sleep(1)
print(color.Yellowbold+"SOUMIA💕")
time.sleep(0.5)
print(color.Whitebold+"tkdbni")
time.sleep(1)
print("mdina s7ara Gmra w jbal")
time.sleep(2)
print("tansayen fiha chi mota tchtebni")
time.sleep(2.5)
print("")
print("")
print("matbdel walo fik a watani")
time.sleep(2)
print("ghada w tatn9ared f din mok")
time.sleep(1.8)
print("AMALI")
time.sleep(0.5)
print("mawslnich bli dnya 3atani")
time.sleep(1.5)
print("l'9ada2 w l9adar ti fsro li anani")
time.sleep(2.4)
print("khbzti ta7t lbat a camarade")
time.sleep(2.5)
print("mab9a tay tochini ta khabar")
time.sleep(2.5)
print("mab9at l7chma mab9a 3arad")
time.sleep(1.7)
print("ki lgrya ki testi ki chabat")
time.sleep(2)
print("")
print("")
print("2020 miladiya w drari mazal tat7ma9o 3adiya")
time.sleep(3)
print("khir w slam khti lmaghribia")
time.sleep(2)
print("baraka matzadi lina 3al TVA")
time.sleep(2.3)
print("")
print("2020 miladiya")
time.sleep(2)
print("w mazal 7asra la venir fl3mariya")
time.sleep(3)
print("wrini ldakhel bach rwat ro7")
time.sleep(2)
print("dik sa3a tji 7lowa lbkariya")
time.sleep(2)
print("")
print("2020 miladiya")
time.sleep(1.5)
print("w mazal tan3so b'riview m3a lfjer")
time.sleep(1.8)
print("li daz 7daya taygol layster")
time.sleep(2)
print("3aych froda ki lhamster")
time.sleep(2)
